name: OpenSky Data Scraper

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scrape_data:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Scrape OpenSky API
        env:
          OPEN_SKY_URL: "https://opensky-network.org/api/states/all"
          USERNAME: ${{ secrets.OPEN_SKY_USERNAME }}
          PASSWORD: ${{ secrets.OPEN_SKY_PASSWORD }}
        run: |
          curl -u "$USERNAME:$PASSWORD" -s "$OPEN_SKY_URL" | jq . > states.json
          timestamp=$(date +"%Y-%m-%d_%H-%M-%S")
          cp states.json "historic/states_$timestamp.json"

      - name: Commit data to repository
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add states.json
          git add historic/states_*.json
          git commit -m "Update OpenSky data"
          git push
