name: OpenSky Data Scraper

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scrape_data:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Scrape OpenSky API
        env:
          OPEN_SKY_URL: "https://opensky-network.org/api/states/all"
          USERNAME: ${{ secrets.OPEN_SKY_USERNAME }}
          PASSWORD: ${{ secrets.OPEN_SKY_PASSWORD }}
        run: |
          # Ensure the historic directory exists
          mkdir -p historic

          # Determine the last timestamp from the previous run
          last_time=0
          if [ -f states.json ]; then
            last_time=$(jq '.time' states.json)
          fi

          # Fetch the latest states data
          curl -u "$USERNAME:$PASSWORD" -s "$OPEN_SKY_URL" | jq . > states.json
          current_time=$(jq '.time' states.json)

          # Calculate 90-second intervals from the last run until now, up to 1 hour
          timestamps=()
          if [ "$last_time" -gt 0 ]; then
            for ((timestamp=last_time+90; timestamp<=current_time; timestamp+=90)); do
              if [ "$timestamp" -ge $((current_time - 3600)) ]; then
                timestamps+=("$timestamp")
              fi
            done
          fi

          # Fetch historic data for each interval
          for timestamp in "${timestamps[@]}"; do
            echo "Fetching states for time $timestamp"
            curl -u "$USERNAME:$PASSWORD" -s "$OPEN_SKY_URL?time=$timestamp" | jq . > "historic/$timestamp.json"
          done

          # Save the latest data to historic folder
          cp states.json "historic/$current_time.json"

      - name: Commit data to repository
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add states.json
          git add historic/*.json
          git commit -m "Update OpenSky data"
          git push
