name: OpenSky Data Scraper

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scrape_data:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Scrape OpenSky API
        env:
          OPEN_SKY_URL: "https://opensky-network.org/api/states/all"
          USERNAME: ${{ secrets.OPEN_SKY_USERNAME }}
          PASSWORD: ${{ secrets.OPEN_SKY_PASSWORD }}
        run: |
          # Fetch current states
          curl -u "$USERNAME:$PASSWORD" -s "$OPEN_SKY_URL" | jq . > states.json
          current_time=$(jq '.time' states.json)

          # Calculate timestamps for 90-second intervals in the past hour
          timestamps=()
          for i in $(seq 90 90 3600); do
            timestamp=$((current_time - i))
            if [ "$timestamp" -ge $((current_time - 3600)) ]; then
              timestamps+=("$timestamp")
            fi
          done

          # Fetch and save historic states
          mkdir -p historic
          for timestamp in "${timestamps[@]}"; do
            echo "Fetching states for time $timestamp"
            curl -u "$USERNAME:$PASSWORD" -s "$OPEN_SKY_URL?time=$timestamp" | jq . > "historic/$timestamp.json"
          done

          # Copy the latest states to historic
          cp states.json "historic/$current_time.json"

      - name: Commit data to repository
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add states.json
          git add historic/*.json
          git commit -m "Update OpenSky data"
          git push
