name: Daily Release and Cleanup

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
    contents: write

jobs:
  release_and_cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Get current date
        id: date
        run: |
          echo "TAG_NAME=$(date '+%Y.%m.%d')" >> $GITHUB_ENV

      - name: Create a new tag
        run: |
          git tag $TAG_NAME
          git push origin $TAG_NAME

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TAG_NAME }}
          release_name: ${{ env.TAG_NAME }}
          body: "Automated daily release for ${{ env.TAG_NAME }}"
          draft: false
          prerelease: false

      - name: Delete JSON files in ./historic/ (keep .gitkeep)
        run: |
          find ./historic/ -type f -name '*.json' -delete

      - name: Commit and push changes
        run: |
          git add ./historic/
          git commit -m "Delete historic JSON files after daily release"
          git push
